In [74]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

features = ['pregnency', 'glucose', 'BP', 'skin', 'insulin', 'BMI', 'DiabetesPedigree', 'age', 'class']
dataset = pd.read_csv('datasets_14370_19291_pima-indians-diabetes.csv', names=features)

df1 = dataset.loc[dataset['class'] == 1]
df2 = dataset.loc[dataset['class'] == 0] 

df1 = df1.replace({'BP':0}, np.median(df1['BP']))
df2 = df2.replace({'BP':0}, np.median(df2['BP']))

df1 = df1.replace({'BMI':0}, np.median(df1['BMI']))
df2 = df2.replace({'BMI':0}, np.median(df2['BMI']))

df1 = df1.replace({'glucose':0}, np.median(df1['glucose']))
df2 = df2.replace({'glucose':0}, np.median(df2['glucose']))

df1 = df1.replace({'skin':0}, np.median(df1['skin']))
df2 = df2.replace({'skin':0}, np.median(df2['skin']))

dataframe = [df1, df2]
dataset = pd.concat(dataframe)

In [75]:
X = dataset.iloc[:,0:8]
Y = dataset.iloc[:,8]

scaler = MinMaxScaler()
X = scaler.fit_transform(X)
print(X)

[[0.35294118 0.67096774 0.48979592 ... 0.31492843 0.23441503 0.48333333]
 [0.47058824 0.89677419 0.40816327 ... 0.10429448 0.25362938 0.18333333]
 [0.         0.6        0.16326531 ... 0.50920245 0.94363792 0.2       ]
 ...
 [0.11764706 0.50322581 0.46938776 ... 0.3803681  0.1118702  0.1       ]
 [0.29411765 0.49677419 0.48979592 ... 0.16359918 0.07130658 0.15      ]
 [0.05882353 0.31612903 0.46938776 ... 0.24948875 0.10119556 0.03333333]]


In [78]:
X_train, X_val, y_train, y_val = train_test_split(X, Y, test_size=0.33, random_state=42)

model = RandomForestClassifier(n_estimators=300, bootstrap = True, max_features = 'sqrt')
model.fit(X_train, y_train)

RandomForestClassifier(max_features='sqrt', n_estimators=300)

In [80]:
model.score(X_val, y_val, sample_weight=None)

0.8661417322834646